- hosts: k3s
  become: yes
  tasks:
    - name: Update apt
      apt: { update_cache: yes }

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install K3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -
      args:
        creates: /usr/local/bin/k3s
